spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  # h2 DB default path: h2-console
  h2:
    console:
      enabled: true
      path: /h2-ui